# Generated by Django 5.0.4 on 2024-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_rename_title_todo_task_remove_todo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
